name: dartins
description: Cordova plugin definitions for use in Dart projects
version: 0.0.2
author: Nathan Kerr <nathanker@gmail.com>
homepage: https://github.com/TheBosZ/dartins
documentation:

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: "0.6.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
